"""Email service: sends AI-generated summaries via SMTP."""

import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from app.config import settings


EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 700px;
            margin: 0 auto;
            padding: 20px;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px 10px 0 0;
            text-align: center;
        }}
        .header h1 {{
            margin: 0;
            font-size: 24px;
        }}
        .header p {{
            margin: 5px 0 0;
            opacity: 0.9;
            font-size: 14px;
        }}
        .content {{
            background: #ffffff;
            padding: 30px;
            border: 1px solid #e0e0e0;
            border-top: none;
            border-radius: 0 0 10px 10px;
        }}
        h2 {{
            color: #667eea;
            border-bottom: 2px solid #667eea;
            padding-bottom: 8px;
            margin-top: 25px;
        }}
        ul {{
            padding-left: 20px;
        }}
        li {{
            margin-bottom: 8px;
        }}
        .footer {{
            text-align: center;
            margin-top: 20px;
            padding: 15px;
            color: #888;
            font-size: 12px;
        }}
        strong {{
            color: #333;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 Sales Insight Report</h1>
        <p>Generated by Rabbitt AI · Sales Insight Automator</p>
    </div>
    <div class="content">
        {summary}
    </div>
    <div class="footer">
        <p>This report was auto-generated by the Rabbitt AI Sales Insight Automator.<br>
        For questions, contact your data analytics team.</p>
    </div>
</body>
</html>
"""


def send_email(to_email: str, summary_html: str, filename: str) -> None:
    """Send the AI-generated summary via SMTP email.

    Args:
        to_email: Recipient email address.
        summary_html: HTML content of the AI summary.
        filename: Original data filename for the subject line.
    """
    if not settings.SMTP_USER or not settings.SMTP_PASSWORD:
        raise ValueError(
            "SMTP credentials are not configured. "
            "Please set SMTP_USER and SMTP_PASSWORD in your .env file."
        )

    # Build the email
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"📊 Sales Insight Report — {filename}"
    msg["From"] = settings.SMTP_FROM or settings.SMTP_USER
    msg["To"] = to_email

    # Plain text fallback
    plain_text = (
        "Your Sales Insight Report is ready. "
        "Please view this email in an HTML-capable client."
    )
    msg.attach(MIMEText(plain_text, "plain"))

    # HTML body
    html_body = EMAIL_TEMPLATE.format(summary=summary_html)
    msg.attach(MIMEText(html_body, "html"))

    # Send via SMTP with TLS
    context = ssl.create_default_context()
    with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
        server.ehlo()
        server.starttls(context=context)
        server.ehlo()
        server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
        server.sendmail(settings.SMTP_USER, to_email, msg.as_string())
